# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-22 04:49
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=250, verbose_name='Blood Group')),
            ],
        ),
        migrations.CreateModel(
            name='DonarRegistation',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('addrees', models.CharField(max_length=250, verbose_name='Address')),
                ('cell_no', models.CharField(max_length=250, verbose_name='Phone Number')),
                ('blood_group', models.CharField(max_length=250, verbose_name='Blood Group')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('location', models.CharField(max_length=225)),
                ('date', models.DateField(default=datetime.date.today)),
                ('blood_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.BloodGroup')),
            ],
        ),
    ]
